apiVersion: v1
kind: PersistentVolume
metadata:
  name: mytimevolume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/apple/TEST/kubevol"
